### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by JackPlaysGames0510** [m4fn3/FakeSticker#1]
I get this error message when I tap on a sticker
![image](https://user-images.githubusercontent.com/48178959/233843266-31c72ffc-afc2-461c-aa13-35c03739cab3.png)

**Comment by m4fn3** [comment]
the error message describes it

**Comment by rspforhp** [comment]
This happens always in dms, and it isn’t true, I can send embed links

**Comment by m4fn3** [comment]
DM is not supported as of now

**Comment by JackPlaysGames0510** [comment]
Is it going to work

**Comment by m4fn3** [comment]
It will be supported soon.

**Comment by JackPlaysGames0510** [comment]
ok that's good to hear
